### ISSUE TITLE
predict.py第131行path变量有点问题

### ISSUE THREAD

**Issue by namemzy** [qixuxiang/Baidu_Lane_Segmentation#1]
predict.py第131行path变量有点问题，每次循环之后path没有重新初始化，继续保留了上一张图片的路径，导致从第二章图片开始就没法再保存。
建议每次循环初始化path=os.getcwd()
或者直接给path绝对路径：path = ‘/[path to your output dir]/' + names[0].split("ColorImage/")[1]

**Comment by qixuxiang** [comment]
@namemzy 好的，谢谢建议，会尽快测试修复
