### ISSUE TITLE
您好，百度网盘链接失效了，压缩文件解压有问题

### ISSUE THREAD

**Issue by namemzy** [qixuxiang/Baidu_Lane_Segmentation#2]
百度网盘链接失效了，压缩文件解压有问题，希望重新上传

顺便问一下
用您的模型跑出来的结果图片都是黑白的，如何才能得到您demo.gif的彩色分割效果，谢谢！

**Comment by qixuxiang** [comment]
文件链接问题我和队友对接下，彩色图是软件合成效果

**Comment by tachikoma777** [comment]
@qixuxiang 网盘的文件仍然有问题，可以重新分享一下吗？多谢！
另外请问这几个模型的分数都是多少呢？

**Comment by tachikoma777** [comment]
用预训练模型multires_unet跑出来结果很差，而且我测试的原图分辨率是3384, 2710，结果图是3384, 1710，请问这个是正常的吗？

**Comment by qixuxiang** [comment]
multires_unet没训练充分，另外队友电脑重装系统了，param文件不在了，建议重新训练。
